- helm_deploy/hmpps-resettlement-passport-person-on-probation-ui/values.yaml
related to https://github.com/ministryofjustice/cloud-platform-environments/pull/20633
> rename ingress certificate

- helm_deploy/hmpps-resettlement-passport-person-on-probation-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Links to Cloud platform change https://github.com/ministryofjustice/cloud-platform-environments/pull/20683
> Ptl 60 rename ingress to shorter name

- .circleci/config.yml
- Dockerfile
Update from template prj https://github.com/ministryofjustice/hmpps-template-typescript/pull/316
> Switch to bookworm-slim to address CVE-2024-0567

- assets/scss/local.scss
- integration_tests/e2e/appointments.cy.ts
- integration_tests/mockApis/psfrApi.ts
- integration_tests/pages/appointment.ts
- server/data/resettlementPassportApiClient.ts
- server/routes/appointment/appointmentController.ts
- server/routes/appointment/index.ts
- server/routes/dashboard/dashboardController.ts
- server/routes/index.ts
- server/services/appointmentService.ts
- server/services/index.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/appointments.njk
- server/views/pages/dashboard.njk
- server/views/partials/subnavigation.njk
> add appointments page and njk utils

- assets/scss/local.scss
- server/data/restClient.test.ts
- server/data/tokenStore/tokenStore.test.ts
- server/routes/appointment/appointmentController.ts
- server/routes/dashboard/dashboardController.ts
- server/routes/dashboard/index.ts
- server/routes/requireUser.ts
- server/services/appointmentService.test.ts
- server/services/appointmentService.ts
- server/services/userService.test.ts
- server/testutils/mockRedisClient.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/appointments.njk
- server/views/pages/dashboard.njk
- server/views/pages/otp.njk
- server/views/partials/header.njk
- server/views/partials/limited-subnavigation.njk
- server/views/partials/subnavigation.njk
> add appointment feed and refactor

- package-lock.json
- package.json
- server/data/resettlementPassportApiClient.ts
- server/routes/appointment/appointmentController.ts
- server/services/appointmentService.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/appointmentDetails.njk
- server/views/pages/appointments.njk
- server/views/partials/appointmentMacro.njk
Adds appointment duration
Adds appointment contact email
Adds google maps link
> Appointments data: add duration and contact email add google maps links

- integration_tests/e2e/appointments.cy.ts
- integration_tests/mockApis/psfrApi.ts
- server/routes/dashboard/dashboardController.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/appointmentDetails.njk
- server/views/pages/appointments.njk
- server/views/pages/dashboard.njk
- server/views/partials/alertBoxMacro.njk
- server/views/partials/appointmentMacro.njk
> add appointment alert box

- integration_tests/e2e/appointments.cy.ts
- integration_tests/e2e/licenceConditions.cy.ts
- server/routes/dashboard/dashboardController.ts
- server/routes/dashboard/index.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/dashboard.njk
- server/views/pages/licenceConditions.njk
> Add appointment tile to dashboard

- helm_deploy/values-prod.yaml
- server/config.ts
- server/services/appointmentService.ts
cache of appointments config:
1 minute dev and preprod
5 minutes prod
> Make appointments cache configurable

- integration_tests/e2e/licenceConditions.cy.ts
- integration_tests/mockApis/psfrApi.ts
- server/data/resettlementPassportApiClient.ts
- server/data/resettlementPassportData.ts
- server/routes/licenceConditions/index.ts
- server/routes/licenceConditions/licenceConditionsController.ts
- server/services/licenceConditionsService.ts
- server/views/pages/licenceConditions.njk
- server/views/pages/licenceConditionsDetails.njk
> Add licence details page

- server/views/pages/index.njk
- server/views/pages/otp.njk
> Update start page content

- README.md
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/e2e/profile.cy.ts
- integration_tests/e2e/settings.cy.ts
- server/config.ts
- server/data/resettlementPassportData.ts
- server/routes/index.ts
- server/routes/profile/index.ts
- server/routes/profile/profileController.ts
- server/routes/settings/index.ts
- server/routes/settings/settingsController.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.ts
- server/views/pages/dashboard.njk
- server/views/pages/profile.njk
- server/views/pages/settings.njk
- server/views/partials/subnavigation.njk
> [PLT-59] profile and settings page

- server/views/pages/otp.njk
> PLT-42 fix otp input field type

- integration_tests/e2e/appointments.cy.ts
- integration_tests/mockApis/psfrApi.ts
- server/routes/appointment/appointmentController.ts
- server/routes/dashboard/dashboardController.ts
- server/routes/otp/otpController.ts
- server/views/pages/appointmentDetails.njk
wraps all controllers in 
```
try {
...
} catch (err) {
return next(err)
}
```
To ensure the node app doesn't crash if there is an exception in the controller
> PLT-153 add extra error handling

- integration_tests/e2e/profile.cy.ts
- server/middleware/setupGovukOneLogin.ts
- server/routes/profile/profileController.ts
- server/views/pages/profile.njk
- Update Mobile content to Phone
- clean login session on errors
> Plt 160 Update Mobile content to Phone

- int-test
- integration_tests/e2e/govukOneLogin.cy.ts
- integration_tests/e2e/notFound.cy.ts
- server/authentication/govukOneLogin.ts
- server/middleware/setupGovukOneLogin.ts
- server/routes/otp/otpController.ts
- server/routes/requireUser.ts
- server/views/pages/index.njk
- server/views/pages/otp.njk
Not found page was not visible if the user wasn't logged in, I had to shift a few things around so now the Not Found is also visible for not authenticated users
> PLT-180 add not logged in route for not found

- integration_tests/e2e/otpVerification.cy.ts
- package-lock.json
- package.json
- server/routes/otp/otpController.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/otp.njk
- Update otp page content
- Update otp page error messages
- Bump npm libraries
> PLT-204 Amend Otp page error messages

- .eslintignore
- pt_tests/README.md
- pt_tests/pages/accountSetup.js
- pt_tests/pages/appointments.js
- pt_tests/pages/dashboard.js
- pt_tests/pages/govOne/govOneCheckEmail.js
- pt_tests/pages/govOne/govOneCreatePassword.js
- pt_tests/pages/govOne/govOneCreatedAccount.js
- pt_tests/pages/govOne/govOneEnterEmail.js
- pt_tests/pages/govOne/govOneEnterOTPSecurityCode.js
- pt_tests/pages/govOne/govOneEnterPassword.js
- pt_tests/pages/govOne/govOneGetOTPSecurityCode.js
- pt_tests/pages/govOne/govOneLogin.js
- pt_tests/pages/licenceConditions.js
- pt_tests/pages/navigationBar.js
- pt_tests/pages/profile.js
- pt_tests/pages/pyfLandingPage.js
- pt_tests/pages/settings.js
- pt_tests/pages/signOut.js
- pt_tests/tests/apiTestsAuth.js
- pt_tests/tests/browserTests.js
- pt_tests/tests/run.js
- tsconfig.json
* Added k6 test framework
* Added browser test for happy path
* Added API tests for all API endpoints
* Added run.js to enable multiple run configurations
* Added README for instructions on how to configure and run tests
* Excluded from lint scanning
> Plt 150 perf test

- integration_tests/e2e/dashboard.cy.ts
- integration_tests/e2e/licenceConditions.cy.ts
- integration_tests/mockApis/psfrApi.ts
- server/views/pages/dashboard.njk
- server/views/pages/licenceConditions.njk
- content updates
- no licence conditions message
> PLT-209: update licence conditions page

- integration_tests/e2e/dashboard.cy.ts
- integration_tests/e2e/errorPage.cy.ts
- integration_tests/mockApis/psfrApi.ts
- server/data/checkError.test.ts
- server/data/checkError.ts
- server/data/personOnProbationApiClient.ts
- server/data/resettlementPassportApiClient.ts
- server/views/pages/dashboard.njk
- server/views/pages/error.njk
> PLT-215 Display the Appointment tile for users who don't have future appointments

- server/views/pages/appointments.njk
> PLT-221: add warning sign

- server/views/pages/dashboard.njk
> PLT-285: Accessibility fix - Use standard font size instead of small

- .circleci/config.yml
- pt_tests/helpers/otpAuth.js
- pt_tests/pages/dashboard.js
- pt_tests/pages/govOne/govOneEnterOTPSecurityCode.js
- pt_tests/pages/govOne/govOneLogin.js
- pt_tests/tests/browserTests.js
- pt_tests/tests/run.js
Added code for getting OTP as OTP client - needed for preprod login
added scenario for preprod browser 
Added config to circle CI for preprod smoke test on main pipeline. 
Updated environment vars to account for pipeline
Updated PT test as part was failing due to dashboard change.
> Plt 290 preprod smoke test

- .circleci/config.yml
- cucumber.json
- security_test/test_security.py
updated for preservation of reports in pipeline
> Plt 309 reports

- README.md
- assets/js/analytics.js
- server/app.ts
- server/data/index.ts
- server/routes/analytics/analyticsController.ts
- server/routes/analytics/index.ts
- server/routes/index.ts
- server/routes/otp/index.ts
- server/routes/otp/otpController.ts
- server/routes/timeout/index.ts
- server/routes/timeout/timeoutController.ts
- server/services/index.ts
- server/utils/analytics.test.ts
- server/utils/analytics.ts
- server/utils/azureAppInsights.test.ts
- server/utils/azureAppInsights.ts
- server/views/pages/appointments.njk
- server/views/pages/licenceConditions.njk
- server/views/pages/overview.njk
- server/views/pages/start.njk
- server/views/partials/appointmentMacro.njk
- server/views/partials/layout.njk
- server/views/partials/limited-subnavigation.njk
- server/views/partials/subnavigation.njk
> PLT-298: Track Event level data in Application Insight 

- .circleci/config.yml
- pt_tests/tests/run.js
- pt_tests/tests/runSmoke.js
updated to run load test in main 
halved load time duration and amount for time in pipeline
> updated PT

- README.md
- assets/js/analytics.js
- server/views/pages/appointments.njk
- server/views/pages/licenceConditions.njk
- server/views/pages/overview.njk
- server/views/pages/start.njk
- server/views/partials/appointmentMacro.njk
- server/views/partials/limited-subnavigation.njk
- server/views/partials/subnavigation.njk
> PLT-298: rename app insight events to be more granular

- server/routes/analytics/analyticsController.ts
- server/routes/otp/otpController.ts
- server/routes/timeout/timeoutController.ts
- server/utils/analytics.ts
> PLT-298: Add missing session and user vars to app insights to distinguish events

- E2E_Tests/test/features/Home.feature
- E2E_Tests/test/steps/commonSteps.ts
added individual email to ensure no test overlap from gov one login
> added individual email to ensure no test overlap from gov one login

- .circleci/config.yml
- E2E_Tests/hooks/hooks.ts
- E2E_Tests/test/features/Home.feature
updated and added screenshot on failure
> Test fix e2e

- server/services/contentfulService.test.ts
- server/services/contentfulService.ts
- server/testutils/mockedContentfulResponse.ts
I was caching the wrong object making the page break on refresh
> PLT-311: fix contentful findbyslug cache issue

- .circleci/config.yml
added workflow for cms to run every 6 hours
> Plt 374 cms circleci

- E2E_Tests/pageObjects/homePage.ts
- E2E_Tests/pageObjects/pyfFooter.ts
- E2E_Tests/test/features/Cms.feature
- E2E_Tests/test/steps/commonSteps.ts
policy pages now checked as part of cms checks
> added scanning for policy pages

- pt_tests/tests/browserTests.js
updated for appointments / hide appointments flag
> ptt-375 Update browserTests.js

- package.json
- security_test/previous_result.json
The new low entries are false positives.
Fix husky deprecation warning
> Fix zap test

- .circleci/config.yml
- security_test/test_security.py
updated config to no longer store artifacts
updated test to only trigger failure on increase of medium to high severity
updated test to trigger warning (not fail) if granular change to previous results
> Fix zap report

- security_test/test_security.py
assertion on results being greater than previous run only.
> Fix zap test assertions

- pt_tests/tests/browserTests.js
No longer experimental so changed lib path
> PT K6 Updated from deprecated version

- package.json
- server/views/pages/appointmentDetails.njk
- server/views/pages/appointments.njk
- server/views/pages/contentfulPage.njk
- server/views/pages/contentfulStartPages.njk
- server/views/pages/documents.njk
- server/views/pages/error.njk
- server/views/pages/feedback-end.njk
- server/views/pages/feedback-questions.njk
- server/views/pages/feedback-review.njk
- server/views/pages/feedback.njk
- server/views/pages/licenceConditions.njk
- server/views/pages/licenceConditionsDetails.njk
- server/views/pages/notFound.njk
- server/views/pages/otp.njk
- server/views/pages/profile.njk
- server/views/pages/settings.njk
- server/views/pages/start.njk
- server/views/pages/timedOut.njk
- server/views/partials/alertBoxMacro.njk
- server/views/partials/applicationInsightsScript.njk
- server/views/partials/appointmentMacro.njk
- server/views/partials/contentfulRelatedLinks.njk
- server/views/partials/header.njk
- server/views/partials/layout.njk
- server/views/partials/limited-subnavigation.njk
- server/views/partials/phasebanner.njk
> Enable prettier on njk files

- .circleci/config.yml
- server/middleware/setUpWebSecurity.ts
To allow application insights script to run
Also save zap test results in circle.
> PLT-476 setup content security policy

- .circleci/config.yml
- security_test/previous_result.json
- server/views/partials/applicationInsightsScript.njk
> PLT-476 Fix cloud role name

- E2E_Tests/test/features/Home.feature
Reduced scenarios around gov one reducing possible 'burned' emails. 
Descoped Gov One login behaviour.
> fix e2e tests

- E2E_Tests/test/features/Home.feature
updated feature file to have correct test tag
> fix - updated tag for e2e tests

- pt_tests/pages/accountSetup.js
- pt_tests/pages/appointments.js
- pt_tests/pages/dashboard.js
- pt_tests/pages/govOne/govOneCheckEmail.js
- pt_tests/pages/govOne/govOneCreatePassword.js
- pt_tests/pages/govOne/govOneCreatedAccount.js
- pt_tests/pages/govOne/govOneEnterEmail.js
- pt_tests/pages/govOne/govOneEnterOTPSecurityCode.js
- pt_tests/pages/govOne/govOneEnterPassword.js
- pt_tests/pages/govOne/govOneGetOTPSecurityCode.js
- pt_tests/pages/govOne/govOneLogin.js
- pt_tests/pages/licenceConditions.js
- pt_tests/pages/navigationBar.js
- pt_tests/pages/profile.js
- pt_tests/pages/pyfLandingPage.js
- pt_tests/pages/settings.js
- pt_tests/pages/signOut.js
- pt_tests/tests/browserTests.js
- pt_tests/tests/run.js
Fix PT tests as new syntax introduced in new k6 version. K6 experimental deprecated. 
* async operations introduced
* some changes to calculation methods
* semicolon coding standards
> updated syntax for all PT test files

- pt_tests/tests/browserTests.js
Update browserTests.js in line with k6 documentation.
> PT-fix updated test assertions 

- integration_tests/e2e/licenceConditions.cy.ts
- server/routes/licenceConditions/licenceConditionsController.ts
> PLT-487 Validate condition id is on the licence

- server/views/partials/contentfulRelatedLinks.njk
That should show on content pages
> PLT-531 Fix missing related/help blocks

- assets/scss/local.scss
- docker-compose.yml
- server/routes/sign-up/signUpController.ts
- server/routes/todo/todoController.test.ts
- server/routes/todo/todoController.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/locales/cy.json
- server/views/locales/en.json
- server/views/pages/todo-list.njk
* Improve styles so table doesn't too wide with large notes/titles
* validate due date is not in the past
> PLT-528 Table layout fix

- .env.example
- README.md
One problem that I had when getting this project running initially was figuring out what configuration I needed and how it should all be set up.
This PR proposes:
* Using a `.env` file rather than setting environment variables on your machine - keeping the config local to the project
* A `.env.example` file which has all the configuration you need out of the box - except any sensitive information
* Comments in the file to show you how to get the sensitive information from the kubernetes cluster
In addition:
* We now specify what you need to have installed in order to run the project
[View full README](https://github.com/ministryofjustice/hmpps-resettlement-passport-person-on-probation-ui/blob/main/README.md)
[View full README](https://github.com/ministryofjustice/hmpps-resettlement-passpor …
> Updated setup guide in README
